services:

  _defaults:
    public: false
    autowire: true

  OxidEsales\GraphQL\Sample\Dao\CategoryDaoInterface:
    class: OxidEsales\GraphQL\Sample\Dao\CategoryDao

  OxidEsales\GraphQL\Sample\Dao\UserDaoInterface:
    class: OxidEsales\GraphQL\Sample\Dao\UserDao

  OxidEsales\GraphQL\Sample\Controller\:
    resource: 'src/Controller/*'
    public: true

  OxidEsales\GraphQL\Sample\Framework\NamespaceMapper:
    class: OxidEsales\GraphQL\Sample\Framework\NamespaceMapper
    tags: ['graphql_namespace_mapper']
