services:

  _defaults:
    public: false
    autowire: true

  OxidEsales\GraphQL\Example\DataType\CategoryExtensionsService:
      class: OxidEsales\GraphQL\Example\DataType\CategoryExtensionsService
      public: true

  OxidEsales\GraphQL\Example\Controller\:
    resource: 'src/Controller/*'
    public: true

  OxidEsales\GraphQL\Example\DataType\:
    resource: 'src/DataType/*Factory.php'
    public: true

  OxidEsales\GraphQL\Example\Framework\NamespaceMapper:
    class: OxidEsales\GraphQL\Example\Framework\NamespaceMapper
    tags: ['graphql_namespace_mapper']

  OxidEsales\GraphQL\Example\Service\PermissionProvider:
    class: OxidEsales\GraphQL\Example\Service\PermissionProvider
    tags: ['graphql_permission_provider']

  OxidEsales\GraphQL\Example\Service\CategoryRepository:
    class: OxidEsales\GraphQL\Example\Service\CategoryRepository
