services:

  _defaults:
    public: false
    autowire: true

  OxidEsales\GraphQL\Example\Dao\CategoryDaoInterface:
    class: OxidEsales\GraphQL\Example\Dao\CategoryDao
    public: true

  OxidEsales\GraphQL\Example\Controller\:
    resource: 'src/Controller/*'
    public: true

  OxidEsales\GraphQL\Example\Framework\NamespaceMapper:
    class: OxidEsales\GraphQL\Example\Framework\NamespaceMapper
    tags: ['graphql_namespace_mapper']
