services:

  _defaults:
    public: false
    autowire: true

  OxidEsales\GraphQl\Sample\Dao\CategoryDaoInterface:
    class: OxidEsales\GraphQl\Sample\Dao\CategoryDao

  OxidEsales\GraphQl\Sample\Type\ObjectType\CategoryType:
    class: OxidEsales\GraphQl\Sample\Type\ObjectType\CategoryType

  OxidEsales\GraphQl\Sample\Type\Provider\CategoryProvider:
    class: OxidEsales\GraphQl\Sample\Type\Provider\CategoryProvider
    tags: ['graphql_query_provider', 'graphql_mutation_provider']

  OxidEsales\GraphQl\Sample\Service\CategoryPermissionsProvider:
    class: OxidEsales\GraphQl\Service\PermissionsProvider
    calls:
      - ['addPermission', ['admin', 'mayaddcategory']]
      - ['addPermission', ['shopadmin', 'mayaddcategory']]
    tags: ['graphql_permissions_provider']
