services:

  _defaults:
    public: false
    autowire: true

  OxidEsales\GraphQL\Sample\Dao\CategoryDaoInterface:
    class: OxidEsales\GraphQL\Sample\Dao\CategoryDao
    public: true

  OxidEsales\GraphQL\Sample\Controllers\:
    resource: 'src/Controllers/*'
    public: true

  OxidEsales\GraphQL\Sample\Framework\NamespaceMapper:
    class: OxidEsales\GraphQL\Sample\Framework\NamespaceMapper
    tags: ['graphql_namespace_mapper']
